### PR TITLE
Worker added to JobInstance Event

### PR DESCRIPTION
**Pull request by splitice**
It would be useful to be able to get the current worker object in the BEFORE_PERFORM event. Particularly this is to enable us to set custom proctitles.

Due to the shared fields and similar purpose I made JobInstanceEvent extend WorkerJobEvent.

Additionally added a guard in Process.php for calling setTitle out of the Process objects own process.

### CODE REVIEW

**Comment by splitice** [comment]
Added:
- PHP 5.4+ is required for testing due to use of short array syntax

**Comment by zomble** [comment]
Hey Mathew,

Thanks once again.

Can you correct the spec file for Resque/Component/Job/Event/JobInstanceEvent missing WorkerInterface use, and add a similar example for the worker. See https://travis-ci.org/php-resque/resque/jobs/67620879#L196

On the PHP version support, I'd like to support 5.3 in the library if I could... I'd prefer to fix my usage of short hand array syntax (I thought I did)... Although I'm not sure of the reasoning (since unsupported etc)... Mmm.

**Comment by zomble** [comment]
Hey Mathew,

Thanks once again!

Can you correct the spec file for Resque/Component/Job/Event/JobInstanceEvent missing WorkerInterface use, and add a similar example as job, and performantjob for the worker. See https://travis-ci.org/php-resque/resque/jobs/67620879#L196

On the PHP version support, I'd like to support 5.3 in the library if I could... I'd prefer to fix my usage of short hand array syntax (I thought I did)... Although I'm not sure of the reasoning (since unsupported etc)... Mmm.

**Comment by splitice** [comment]
Personally I couldnt care less about 5.3 support, its two versions behind. The library still works, just cant be tested in 5.3 currently. I can do it though if thats the way you want to go.

I dont know much (anything) about phpspec currently. So I have refrained from making modifications except where missing classes / interfaces are concerned.

**Comment by zomble** [comment]
No worries.

Have a look at 0d5d496f522 to see the corresponding spec file changes for JobInstanceEvent.

**Pull request merged**
